data-source:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/appointment?serverTimezone=UTC
    username: root
    password: xuyangliu99.
    driver-class-name: com.mysql.cj.jdbc.Driver
  postgresql:
    url: jdbc:postgresql://192.168.5.221:28466/dw
    username: postgres
    password: abc@123
    driver-class-name: org.postgresql.Driver
  redis:
    host: 192.168.5.162
    port: 6379
    database: 0
    max-active: 100
    max-idle: 100
    min-idle: 50
    max-wait: 6000
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    scheme: http
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
